// This file was generated by [tauri-specta]. Do not edit this file manually.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Pre-resolve media paths (e.g. Android Content URIs to cached files).
	 *  Never fails wholesale — each path carries its own optional error so one
	 *  bad URI cannot blank out the whole batch.
	 */
	resolveMediaPaths: (paths: string[]) => __TAURI_INVOKE<ResolvedMediaPath[]>("resolve_media_paths", { paths }),
	statMediaPaths: (paths: string[]) => __TAURI_INVOKE<StatMediaPath[]>("stat_media_paths", { paths }),
	/**
	 *  Explicitly delete a previously staged Android input file (user removed
	 *  the row / cleared the list). No-op on desktop and for any path outside
	 *  the app's staging directory.
	 */
	deleteStagedInput: (path: string) => __TAURI_INVOKE<void>("delete_staged_input", { path }),
	hasMediaPermissions: () => __TAURI_INVOKE<boolean>("has_media_permissions"),
	requestMediaPermissions: () => __TAURI_INVOKE<void>("request_media_permissions"),
	openAppSettings: () => __TAURI_INVOKE<void>("open_app_settings"),
	/**
	 *  Probe files for the UI list in parallel with a bounded worker pool.
	 *  Per-file errors land in `FileMeta.error` instead of failing the whole
	 *  call. Runs asynchronously without blocking Tauri's main loop.
	 */
	probeFiles: (paths: string[]) => __TAURI_INVOKE<FileMeta[]>("probe_files", { paths }),
	/**
	 *  Enqueue a conversion batch; returns job ids. Each input carries its own
	 *  optional trim window (`startTime`/`endTime` in seconds, both nullable).
	 */
	startConversion: (items: TrimSpec[], options: ConversionOptions, concurrency: number | null) => typedError<string[], AppError>(__TAURI_INVOKE("start_conversion", { items, options, concurrency })),
	/**
	 *  Waveform peaks for the trim editor UI. Decodes only the first audio
	 *  stream (audio-only decode; no video work) into `buckets` min/max pairs.
	 *  Runs in a dedicated background task to prevent any UI freezing.
	 */
	waveformPeaks: (path: string, buckets: number | null) => typedError<([(number | null), (number | null)])[], AppError>(__TAURI_INVOKE("waveform_peaks", { path, buckets })),
	cancelJob: (jobId: string) => __TAURI_INVOKE<void>("cancel_job", { jobId }),
	cancelAllJobs: () => __TAURI_INVOKE<void>("cancel_all_jobs"),
	clearFinished: () => __TAURI_INVOKE<void>("clear_finished"),
	getQueue: () => __TAURI_INVOKE<JobRecord[]>("get_queue"),
	/**  Pre-flight disk space query for the chosen output location. */
	diskFree: (path: string) => typedError<DiskFree, AppError>(__TAURI_INVOKE("disk_free", { path })),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	saveSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	logFrontend: (level: string, msg: string) => __TAURI_INVOKE<void>("log_frontend", { level, msg }),
};

/* Types */
export type AppError = { kind: "Io"; message: string } | { kind: "FFmpeg"; message: string } | { kind: "NoAudioTrack"; message: string } | { kind: "CorruptedFile"; message: string } | { kind: "InsufficientDiskSpace"; message: {
	needed: number,
	available: number,
} } | { kind: "InvalidInput"; message: string } | { kind: "Cancelled" } | { kind: "NotFound"; message: string } | { kind: "Other"; message: string };

export type AudioFormat = "mp3" | "wav" | "aac" | "m4a" | "flac" | "opus";

export type ConversionOptions = {
	format: AudioFormat,
	quality: QualityPreset,
	/**  Used when quality == Custom. kbps. */
	customBitrateKbps: number | null,
	sampleRateHz: number | null,
	channels: number | null,
	splitEnabled: boolean,
	/**  Part duration in seconds (accepts minutes*60 or HH:MM:SS from UI). */
	splitDurationSecs: number | null,
	removeSilence: boolean,
	/**  Negative dB threshold, e.g. -30. */
	silenceThresholdDb: number,
	silenceMinDurationSecs: number | null,
	outputMode: OutputMode,
	/**  Required when output_mode == CustomFolder. */
	customOutputDir: string | null,
};

export type DiskFree = {
	free_bytes: number,
};

export type FileMeta = {
	name: string,
	path: string,
	sizeBytes: number,
	durationSecs: number | null,
	formatName: string,
	hasAudio: boolean,
	error: string | null,
};

/**  Snapshot of one job, serialized to the frontend. */
export type JobRecord = {
	id: string,
	sourcePath: string,
	status: JobStatus,
	percent: number | null,
	speed: string | null,
	error: string | null,
	technical: string | null,
	warning: string | null,
	outputs: string[],
};

export type JobStatus = "waiting" | "processing" | "completed" | "failed" | "cancelled";

/**  Where output files are written. */
export type OutputMode = 
/**  Next to the source file. */
"same_as_source" | 
/**  In a user-chosen folder; one subfolder per source when multiple files. */
"custom_folder" | 
/**  Auto-created per-source-file subfolder next to the source. */
"per_source_folder";

export type QualityPreset = "low" | "medium" | "high" | "very_high" | "custom";

/**
 *  Result of pre-resolving one input path (e.g. Android Content URIs to
 *  cached local files). `resolved` equals `input` when no staging happened
 *  or when staging failed (the error field then explains why).
 */
export type ResolvedMediaPath = {
	input: string,
	resolved: string,
	error: string | null,
};

export type Settings = {
	language: string,
	theme: string,
	defaultFormat: AudioFormat,
	defaultQuality: QualityPreset,
	defaultOutputMode: OutputMode,
	defaultOutputDir: string | null,
	autoOpenOutputFolder: boolean,
	concurrency: number,
	removeSilenceDefault: boolean,
	silenceThresholdDb: number,
	silenceMinDurationSecs: number | null,
	/**  Advanced/debug only: override bundled ffmpeg location. */
	ffmpegPathOverride: string | null,
};

/**
 *  One entry of `stat_media_paths`: lightweight metadata for a picked URI —
 *  NO file copying (staging happens lazily right before each conversion).
 */
export type StatMediaPath = {
	input: string,
	name: string,
	sizeBytes: number,
	durationSecs: number,
	error: string | null,
};

/**
 *  Optional per-file trim window, in seconds. Both bounds optional: a `None`
 *  bound means "until the start/end of the file". Serialized as
 *  `{ path, startTime, endTime }` from the frontend (camelCase, seconds).
 */
export type TrimSpec = {
	path: string,
	/**  Fast-seek position; inserted BEFORE `-i` when present. */
	startTimeSecs: number | null,
	/**  Stop position; inserted AFTER `-i` as `-to` when present. */
	endTimeSecs: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

