// This file was generated by [tauri-specta]. Do not edit this file manually.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Pre-resolve media paths (e.g. Android Content URIs to cached files).
	 *  Never fails wholesale — each path carries its own optional error so one
	 *  bad URI cannot blank out the whole batch.
	 */
	resolveMediaPaths: (paths: string[]) => __TAURI_INVOKE<ResolvedMediaPath[]>("resolve_media_paths", { paths }),
	/**
	 *  Lightweight metadata lookup (name / size / duration) for the picked
	 *  paths/URIs. Never fails wholesale — each path carries its own error.
	 */
	statMediaPaths: (paths: string[]) => __TAURI_INVOKE<StatMediaPath[]>("stat_media_paths", { paths }),
	/**
	 *  Explicitly delete a previously staged Android input file (user removed
	 *  the row / cleared the list). No-op on desktop and for any path outside
	 *  the app's staging directory.
	 */
	deleteStagedInput: (path: string) => __TAURI_INVOKE<void>("delete_staged_input", { path }),
	/**
	 *  Whether the required media permissions are granted (Android). Always true
	 *  on desktop.
	 */
	hasMediaPermissions: () => __TAURI_INVOKE<boolean>("has_media_permissions"),
	/**  Trigger the Android runtime permission dialog (no-op on desktop). */
	requestMediaPermissions: () => __TAURI_INVOKE<void>("request_media_permissions"),
	/**  Open the system app-settings page so the user can grant permissions. */
	openAppSettings: () => __TAURI_INVOKE<void>("open_app_settings"),
	/**
	 *  Probe files for the UI list in parallel with a bounded worker pool.
	 *  Per-file errors land in `FileMeta.error` instead of failing the whole
	 *  call. Runs asynchronously without blocking Tauri's main loop.
	 */
	probeFiles: (paths: string[]) => __TAURI_INVOKE<FileMeta[]>("probe_files", { paths }),
	/**
	 *  Enqueue a conversion batch; returns job ids. Each input carries its own
	 *  optional trim window (`startTime`/`endTime` in seconds, both nullable).
	 */
	startConversion: (items: TrimSpec[], options: ConversionOptions, concurrency: number | null) => typedError<string[], AppError>(__TAURI_INVOKE("start_conversion", { items, options, concurrency })),
	/**
	 *  Waveform peaks for the trim editor UI. Decodes only the first audio
	 *  stream (audio-only decode; no video work) into `buckets` min/max pairs.
	 *  Runs in a dedicated background task to prevent any UI freezing.
	 */
	waveformPeaks: (path: string, buckets: number | null) => typedError<([(number | null), (number | null)])[], AppError>(__TAURI_INVOKE("waveform_peaks", { path, buckets })),
	cancelJob: (jobId: string) => __TAURI_INVOKE<void>("cancel_job", { jobId }),
	cancelAllJobs: () => __TAURI_INVOKE<void>("cancel_all_jobs"),
	clearFinished: () => __TAURI_INVOKE<void>("clear_finished"),
	getQueue: () => __TAURI_INVOKE<JobRecord[]>("get_queue"),
	/**  Pre-flight disk space query for the chosen output location. */
	diskFree: (path: string) => typedError<DiskFree, AppError>(__TAURI_INVOKE("disk_free", { path })),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	saveSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	logFrontend: (level: string, msg: string) => __TAURI_INVOKE<void>("log_frontend", { level, msg }),
	/**  Volume analysis for a media file (peak dB, mean dB, suggested gain). */
	analyzeAudioVolume: (path: string, startSecs: number | null, durationSecs: number | null) => typedError<VolumeAnalysis, AppError>(__TAURI_INVOKE("analyze_audio_volume", { path, startSecs, durationSecs })),
	/**  Fast A/B preview snippet generator for Sound Booster. */
	generateAbPreview: (path: string, preset: BoosterPreset, manualGainPercent: number | null, startTimeSecs: number | null, durationSecs: number | null) => typedError<AbPreviewResult, AppError>(__TAURI_INVOKE("generate_ab_preview", { path, preset, manualGainPercent, startTimeSecs, durationSecs })),
	/**  Enqueue sound booster batch conversion. */
	startSoundBoost: (items: BoosterJobSpec[], options: ConversionOptions, concurrency: number | null) => typedError<string[], AppError>(__TAURI_INVOKE("start_sound_boost", { items, options, concurrency })),
	/**
	 *  Scan system audio files across platforms (MediaStore on Android, standard music/user directories on desktop).
	 *  Sorted by default by latest date added (created/modified timestamp descending).
	 */
	scanAudioFiles: (customDirs: string[] | null) => __TAURI_INVOKE<AudioTrackInfo[]>("scan_audio_files", { customDirs }),
	/**  Check music permission status across platforms. */
	getMusicPermissionStatus: () => __TAURI_INVOKE<LibraryPermissionStatus>("get_music_permission_status"),
	/**  Delete audio track from the device library. */
	deleteAudioTrack: (pathOrUri: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_audio_track", { pathOrUri })),
	/**  Set track as default ringtone (Android). */
	setAsRingtone: (pathOrUri: string) => typedError<null, AppError>(__TAURI_INVOKE("set_as_ringtone", { pathOrUri })),
	/**  Share track via system share sheet. */
	shareAudioTrack: (pathOrUri: string, title: string, mimeType: string) => typedError<null, AppError>(__TAURI_INVOKE("share_audio_track", { pathOrUri, title, mimeType })),
	/**  Play a track or playlist via native Jetpack Media3 (Android). */
	androidPlayerPlay: (trackJson: string, playlistJson: string | null, startIndex: number | null) => typedError<string, AppError>(__TAURI_INVOKE("android_player_play", { trackJson, playlistJson, startIndex })),
	/**  Pause playback via native Jetpack Media3. */
	androidPlayerPause: () => typedError<string, AppError>(__TAURI_INVOKE("android_player_pause")),
	/**  Resume playback via native Jetpack Media3. */
	androidPlayerResume: () => typedError<string, AppError>(__TAURI_INVOKE("android_player_resume")),
	/**  Seek playback to timestamp in milliseconds via native Jetpack Media3. */
	androidPlayerSeekTo: (positionMs: number) => typedError<string, AppError>(__TAURI_INVOKE("android_player_seek_to", { positionMs })),
	/**  Skip to next media item via native Jetpack Media3. */
	androidPlayerNext: () => typedError<string, AppError>(__TAURI_INVOKE("android_player_next")),
	/**  Skip to previous media item via native Jetpack Media3. */
	androidPlayerPrevious: () => typedError<string, AppError>(__TAURI_INVOKE("android_player_previous")),
	/**  Set repeat mode ('off', 'one', 'all') via native Jetpack Media3. */
	androidPlayerSetRepeatMode: (mode: string) => typedError<string, AppError>(__TAURI_INVOKE("android_player_set_repeat_mode", { mode })),
	/**  Set shuffle mode enabled/disabled via native Jetpack Media3. */
	androidPlayerSetShuffleMode: (enabled: boolean) => typedError<string, AppError>(__TAURI_INVOKE("android_player_set_shuffle_mode", { enabled })),
	/**  Set playback speed (e.g. 1.0, 1.25) via native Jetpack Media3. */
	androidPlayerSetSpeed: (speed: number | null) => typedError<string, AppError>(__TAURI_INVOKE("android_player_set_speed", { speed })),
	/**  Set output volume fraction (0.0..1.0) via native Jetpack Media3. */
	androidPlayerSetVolume: (volume: number | null) => typedError<string, AppError>(__TAURI_INVOKE("android_player_set_volume", { volume })),
	/**  Stop playback via native Jetpack Media3. */
	androidPlayerStop: () => typedError<string, AppError>(__TAURI_INVOKE("android_player_stop")),
	/**  Query live playback state from native Jetpack Media3. */
	androidPlayerGetState: () => __TAURI_INVOKE<string>("android_player_get_state"),
	/**  Query and drain any files/URIs opened by the OS (e.g. cold-start or before frontend event listeners registered). */
	getPendingOpenFiles: () => typedError<string[], AppError>(__TAURI_INVOKE("get_pending_open_files")),
	/**  Resolve a single audio file path or content:// URI into an AudioTrackInfo struct. */
	resolveAudioTrack: (pathOrUri: string) => typedError<AudioTrackInfo, AppError>(__TAURI_INVOKE("resolve_audio_track", { pathOrUri })),
	/**
	 *  Exit the app (used for Android double-back-to-exit).
	 *  On desktop this terminates via Tauri; on Android the Kotlin
	 *  `exitApp` bridge finishes the activity.
	 */
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
};

/* Types */
export type AbPreviewResult = {
	originalPath: string,
	boostedPath: string,
	snippetStartSecs: number | null,
	snippetDurationSecs: number | null,
	originalPeaks: ([(number | null), (number | null)])[],
	boostedPeaks: ([(number | null), (number | null)])[],
	analysis: VolumeAnalysis,
};

export type AppError = { kind: "Io"; message: string } | { kind: "FFmpeg"; message: string } | { kind: "NoAudioTrack"; message: string } | { kind: "CorruptedFile"; message: string } | { kind: "InsufficientDiskSpace"; message: {
	needed: number,
	available: number,
} } | { kind: "InvalidInput"; message: string } | { kind: "Cancelled" } | { kind: "NotFound"; message: string } | { kind: "Unsupported"; message: string } | { kind: "Other"; message: string };

export type AudioFormat = "mp3" | "wav" | "aac" | "m4a" | "flac" | "opus";

export type AudioTrackInfo = {
	id: string,
	uri: string,
	path: string | null,
	name: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	durationSecs: number | null,
	sizeBytes: number,
	modifiedTimestampMs: number,
	createdTimestampMs: number,
	format: string,
	mimeType: string,
	coverUrl: string | null,
};

export type BoosterJobSpec = {
	trim: TrimSpec,
	preset: BoosterPreset,
	manualGainPercent: number | null,
};

/**  The 5 official booster presets + manual mode. */
export type BoosterPreset = 
/**  Automatic dynamic gain based on dynamic normalizer + limiter (Default). */
"smart" | 
/**  Balanced boost tuned for music (+6 dB default or safe headroom + limiter). */
"music" | 
/**  Speech-optimized boost with low-cut filter (highpass 80Hz) to remove rumble. */
"voice" | 
/**  Low-end emphasis (bass boost + dynaudnorm + limiter) for bass-heavy audio. */
"bass" | 
/**  Maximum amplification with strict limiter — surfaces quality warning in UI. */
"extreme" | 
/**  User-controlled slider (0% to 200%). */
"manual";

export type ConversionOptions = {
	format: AudioFormat,
	quality: QualityPreset,
	/**  Used when quality == Custom. kbps. */
	customBitrateKbps: number | null,
	sampleRateHz: number | null,
	channels: number | null,
	splitEnabled: boolean,
	/**  Part duration in seconds (accepts minutes*60 or HH:MM:SS from UI). */
	splitDurationSecs: number | null,
	removeSilence: boolean,
	/**  Negative dB threshold, e.g. -30. */
	silenceThresholdDb: number,
	silenceMinDurationSecs: number | null,
	outputMode: OutputMode,
	/**  Required when output_mode == CustomFolder. */
	customOutputDir: string | null,
	boostEnabled?: boolean,
	boostPreset?: BoosterPreset | null,
	boostManualGainPercent?: number | null,
};

export type DiskFree = {
	free_bytes: number,
};

export type FileMeta = {
	name: string,
	path: string,
	sizeBytes: number,
	durationSecs: number | null,
	formatName: string,
	hasAudio: boolean,
	error: string | null,
};

/**  Snapshot of one job, serialized to the frontend. */
export type JobRecord = {
	id: string,
	sourcePath: string,
	status: JobStatus,
	percent: number | null,
	speed: string | null,
	error: string | null,
	technical: string | null,
	warning: string | null,
	outputs: string[],
};

export type JobStatus = "waiting" | "processing" | "completed" | "failed" | "cancelled";

export type LibraryPermissionStatus = "granted" | "denied" | "permanentlyDenied" | "restricted" | "notRequired";

/**  Where output files are written. */
export type OutputMode = 
/**  Next to the source file. */
"same_as_source" | 
/**  In a user-chosen folder; one subfolder per source when multiple files. */
"custom_folder" | 
/**  Auto-created per-source-file subfolder next to the source. */
"per_source_folder";

export type QualityPreset = "low" | "medium" | "high" | "very_high" | "custom";

/**
 *  Result of pre-resolving one input path (e.g. Android Content URIs to
 *  cached local files). `resolved` equals `input` when no staging happened
 *  or when staging failed (the error field then explains why).
 */
export type ResolvedMediaPath = {
	input: string,
	resolved: string,
	error: string | null,
};

export type Settings = {
	language: string,
	theme: string,
	defaultFormat: AudioFormat,
	defaultQuality: QualityPreset,
	defaultOutputMode: OutputMode,
	defaultOutputDir: string | null,
	autoOpenOutputFolder: boolean,
	concurrency: number,
	removeSilenceDefault: boolean,
	silenceThresholdDb: number,
	silenceMinDurationSecs: number | null,
	/**  Advanced/debug only: override bundled ffmpeg location. */
	ffmpegPathOverride: string | null,
};

/**
 *  One entry of `stat_media_paths`: lightweight metadata for a picked URI —
 *  NO file copying (staging happens lazily right before each conversion).
 */
export type StatMediaPath = {
	input: string,
	name: string,
	sizeBytes: number,
	durationSecs: number | null,
	error: string | null,
};

/**
 *  Optional per-file trim window, in seconds. Both bounds optional: a `None`
 *  bound means "until the start/end of the file". Serialized as
 *  `{ path, startTime, endTime }` from the frontend (camelCase, seconds).
 */
export type TrimSpec = {
	path: string,
	/**  Fast-seek position; inserted BEFORE `-i` when present. */
	startTimeSecs: number | null,
	/**  Stop position; inserted AFTER `-i` as `-to` when present. */
	endTimeSecs: number | null,
	boostEnabled?: boolean | null,
	boostPreset?: BoosterPreset | null,
	boostManualGainPercent?: number | null,
};

/**  Results of audio volume analysis via `volumedetect`. */
export type VolumeAnalysis = {
	/**  Peak volume in dB (e.g. -6.5 dB). 0 dB represents full scale digital max. */
	maxVolumeDb: number | null,
	/**  Mean volume in dB (e.g. -22.3 dB). */
	meanVolumeDb: number | null,
	/**  Calculated safe boost gain in dB to reach close to peak without compression. */
	suggestedGainDb: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

