pub mod android_fs;
mod commands;
pub mod disk;
pub mod error;
pub mod ffmpeg;
pub mod logger;
pub mod processing;
pub mod queue;
pub mod settings;
pub mod types;

#[cfg(target_os = "android")]
#[no_mangle]
pub extern "C" fn Java_com_audioconverter_app_MainActivity_initNativePaths(
    mut env: jni::JNIEnv,
    _class: jni::objects::JClass,
    native_lib_dir: jni::objects::JString,
    cache_dir: jni::objects::JString,
) {
    if let Ok(vm) = env.get_java_vm() {
        android_fs::set_java_vm(vm);
    }
    // This is a Java-invoked native method, so FindClass resolves app classes
    // via MainActivity's classloader — the ONLY safe place to capture the
    // class reference for later use on background (attached) threads.
    android_fs::cache_main_activity_class(&mut env);
    if let Ok(dir) = env.get_string(&native_lib_dir) {
        let dir_str: String = dir.into();
        std::env::set_var("TAURI_ANDROID_NATIVE_LIB_DIR", &dir_str);
        log_info!("Android JNI: TAURI_ANDROID_NATIVE_LIB_DIR={}", dir_str);
    }
    if let Ok(dir) = env.get_string(&cache_dir) {
        let dir_str: String = dir.into();
        std::env::set_var("TAURI_ANDROID_CACHE_DIR", &dir_str);
        log_info!("Android JNI: TAURI_ANDROID_CACHE_DIR={}", dir_str);
    }
}

/// Registered by the Android runtime the moment `libaudio_converter.so` is
/// loaded — independent of MainActivity lifecycle, so the JNI bridge works
/// even if `initNativePaths` was never called (or failed) in Kotlin.
#[cfg(target_os = "android")]
#[no_mangle]
pub extern "system" fn JNI_OnLoad(
    vm: *mut jni::sys::JavaVM,
    _reserved: *mut std::ffi::c_void,
) -> jni::sys::jint {
    match unsafe { jni::JavaVM::from_raw(vm) } {
        Ok(vm) => {
            if let Ok(mut env) = vm.get_env() {
                android_fs::cache_main_activity_class(&mut env);
            }
            android_fs::set_java_vm(vm);
            log_info!("Android JNI_OnLoad: JavaVM registered");
            jni::sys::JNI_VERSION_1_6
        }
        Err(e) => {
            log_error!("Android JNI_OnLoad failed: {e}");
            jni::sys::JNI_ERR
        }
    }
}

use tauri::{Manager, RunEvent};

pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::resolve_media_paths,
        commands::stat_media_paths,
        commands::delete_staged_input,
        commands::has_media_permissions,
        commands::request_media_permissions,
        commands::open_app_settings,
        commands::probe_files,
        commands::start_conversion,
        commands::waveform_peaks,
        commands::cancel_job,
        commands::cancel_all_jobs,
        commands::clear_finished,
        commands::get_queue,
        commands::disk_free,
        commands::get_settings,
        commands::save_settings,
        commands::log_frontend,
        commands::analyze_audio_volume,
        commands::generate_ab_preview,
        commands::start_sound_boost,
        commands::start_live_boost,
        commands::stop_live_boost,
        commands::set_live_boost_gain,
        commands::get_live_boost_status,
        commands::is_live_boost_supported,
    ])
}

/// App entry point (called from main.rs).
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(all(debug_assertions, not(mobile), not(target_os = "android"), not(target_os = "ios")))]
    {
        let out_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("src/types/generated.ts");
        let _ = builder.export(
            specta_typescript::Typescript::default()
                .header("// This file was generated by [tauri-specta]. Do not edit this file manually.\n\n"),
            &out_path,
        );
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let data_dir = app
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| std::env::temp_dir().join("audio-converter"));
            settings::init_app_data_dir(data_dir);
            app.manage(queue::QueueManager::new(app.handle().clone()));
            log_info!("app started");
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .build(tauri::generate_context!())
        .expect("error while building audio converter")
        .run(|app_handle, event| {
            // Kill any in-flight ffmpeg children when the app quits;
            // otherwise they outlive the process as orphans.
            if matches!(event, RunEvent::ExitRequested { .. } | RunEvent::Exit) {
                use tauri::Manager as _;
                app_handle.state::<queue::QueueManager>().cancel_all();
            }
        });
}
