pub mod android_fs;
mod commands;
pub mod disk;
pub mod error;
pub mod ffmpeg;
pub mod logger;
pub mod processing;
pub mod queue;
pub mod settings;
pub mod types;

#[cfg(target_os = "android")]
#[no_mangle]
pub extern "C" fn Java_com_audioconverter_app_MainActivity_initNativePaths(
    mut env: jni::JNIEnv,
    _class: jni::objects::JClass,
    native_lib_dir: jni::objects::JString,
    cache_dir: jni::objects::JString,
) {
    if let Ok(vm) = env.get_java_vm() {
        android_fs::set_java_vm(vm);
    }
    if let Ok(dir) = env.get_string(&native_lib_dir) {
        let dir_str: String = dir.into();
        std::env::set_var("TAURI_ANDROID_NATIVE_LIB_DIR", &dir_str);
        log_info!("Android JNI: TAURI_ANDROID_NATIVE_LIB_DIR={}", dir_str);
    }
    if let Ok(dir) = env.get_string(&cache_dir) {
        let dir_str: String = dir.into();
        std::env::set_var("TAURI_ANDROID_CACHE_DIR", &dir_str);
        log_info!("Android JNI: TAURI_ANDROID_CACHE_DIR={}", dir_str);
    }
}

use tauri::{Manager, RunEvent};

pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::resolve_media_paths,
        commands::probe_files,
        commands::start_conversion,
        commands::waveform_peaks,
        commands::cancel_job,
        commands::cancel_all_jobs,
        commands::clear_finished,
        commands::get_queue,
        commands::disk_free,
        commands::get_settings,
        commands::save_settings,
        commands::log_frontend,
    ])
}

/// App entry point (called from main.rs).
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    {
        let out_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("src/types/generated.ts");
        builder
            .export(
                specta_typescript::Typescript::default()
                    .header("// This file was generated by [tauri-specta]. Do not edit this file manually.\n\n"),
                &out_path,
            )
            .expect("Failed to export typescript bindings");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let data_dir = app
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| std::env::temp_dir().join("audio-converter"));
            settings::init_app_data_dir(data_dir);
            app.manage(queue::QueueManager::new(app.handle().clone()));
            log_info!("app started");
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .build(tauri::generate_context!())
        .expect("error while building audio converter")
        .run(|app_handle, event| {
            // Kill any in-flight ffmpeg children when the app quits;
            // otherwise they outlive the process as orphans.
            if matches!(event, RunEvent::ExitRequested { .. } | RunEvent::Exit) {
                use tauri::Manager as _;
                app_handle.state::<queue::QueueManager>().cancel_all();
            }
        });
}
