fn main() {
    let builder = audio_converter::specta_builder();
    let out_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("src/types/generated.ts");
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// This file was generated by [tauri-specta]. Do not edit this file manually.\n\n"),
            &out_path,
        )
        .expect("Failed to export typescript bindings");
    println!("Successfully exported TypeScript bindings to {}", out_path.display());
}
